Greeting.create!(id: 1, message: "Hello")
Greeting.create!(id: 2, message: "Hey")
Greeting.create!(id: 3, message: "Hi")
Greeting.create!(id: 4, message: "Good Morning")
Greeting.create!(id: 5, message: "Good afternoon")
Greeting.create!(id: 6, message: "Good evening")
Greeting.create!(id: 7, message: "Bonjour")
Greeting.create!(id: 8, message: "Bonsoir")
Greeting.create!(id: 9, message: "What's up?")
Greeting.create!(id: 10, message: "How are you?")